defaults:
  - paths: 42_cluster
  - _self_
  - augmentations: asymmetric.yaml
  - wandb: private.yaml
  - override hydra/hydra_logging: disabled
  - override hydra/job_logging: disabled

# disable hydra outputs
hydra:
  output_subdir: null
  run:
    dir: .

name: "mocov3-ego4d-blur-nosal-gpu-aug"
method: "mocov3"
backbone:
  name: "resnet50"
method_kwargs:
  proj_hidden_dim: 4096
  proj_output_dim: 256
  pred_hidden_dim: 4096
  temperature: 0.1
  layers_proj: 3 
  layers_pred: 2
momentum:
  base_tau: 0.996
  final_tau: 0.996
data:
  dataset: ego4d
  train_path: ${paths.data_train_path}
  val_path: None
  format: "h5"
  num_workers: 8
  gpu_augmentation: True
  gpu_pre_image_size: 540
  dataset_kwargs:
    time_window: 15
    foveation:
      type: "blur"
      crop:
        crop_size: 336
      blur:
        radii_frac: [0.3, 0.7]
        sigma_base_frac: 0.006
        sigma_growth: 2
        saliency_alpha: 0.0
        transition_frac: 0.1
      cm:
        fov_ratio: 0.3125
        K_ratio: 0.208
        saliency_beta: 1.0
optimizer:
  name: "lars"
  batch_size: 128
  lr: 3.0
  classifier_lr: 3e-3
  weight_decay: 1e-6
  no_labels: True
scheduler:
  name: "warmup_cosine"
  warmup_epochs: 3  # should be roughly 10% of total epochs
checkpoint:
  enabled: True
  dir: ${paths.checkpoint_dir}
  frequency: 5
  keep_prev: True
  save_last: True
auto_resume:
  enabled: True
knn_clb:
  enabled: True
  dataset: imagenet100_42
  train_path:  ${paths.knn_clb_train_path}
  val_path:  ${paths.knn_clb_val_path}
  num_workers: 4
  batch_size: 16
  k: [ 10, 20, 50, 100 ]
  perform_on_validation: True
  verbose: True


# overwrite PL stuff
max_epochs: 30
devices: 4
sync_batchnorm: True
accelerator: "gpu"
strategy: ddp
precision: 16-mixed
no_validation: True # important since we have no validation split
limit_val_batches: 0
num_sanity_val_steps: 0
log_every_n_steps: 100 # increase for larger runs
limit_train_batches: 1.0 # percentile or total batches (1.0 for full run)