defaults:
  - _self_
  - augmentations: asymmetric.yaml
  - wandb: private.yaml
  - override hydra/hydra_logging: disabled
  - override hydra/job_logging: disabled

# disable hydra outputs
hydra:
  output_subdir: null
  run:
    dir: .

name: "fov-parameter-test"
method: "mocov3"
backbone:
  name: "resnet50"
method_kwargs:
  proj_hidden_dim: 4096
  proj_output_dim: 256
  pred_hidden_dim: 4096
  temperature: 0.1
  layers_proj: 3 
  layers_pred: 2
momentum:
  base_tau: 0.996
  final_tau: 0.996
data:
  dataset: ego4d
  train_path: "/home/data/elias/Ego4dDivSubset"
  val_path: None
  format: "h5"
  num_workers: 4
  dataset_kwargs:
    time_window: 15
    foveation:
      type: "fcg"
      crop:
        crop_size: 336
      blur:
      # change blur logic to include scalars for sigmas & rings!
        saliency_alpha: 1.0
        transition_width: 32
      fcg:
        p0: 64
        alpha: 0.5
        beta: 0.0
optimizer:
  name: "lars"
  batch_size: 256
  lr: 3.0
  classifier_lr: 3e-3
  weight_decay: 1e-6
  no_labels: True
scheduler:
  name: "warmup_cosine"
  warmup_epochs: 2  # should be roughly 10% of total epochs
checkpoint:
  enabled: True
  dir: "/home/data/elias/trained_models"
  frequency: 1
  keep_prev: False
auto_resume:
  enabled: True
knn_clb:
  enabled: True
  dataset: imagenet100
  train_path:  "/home/data/elias/imagenet100/train"
  val_path:  "/home/data/elias/imagenet100/val"
  num_workers: 4
  batch_size: 16
  k: [ 10, 20, 50, 100 ]
  perform_on_validation: True
  verbose: True


# overwrite PL stuff
max_epochs: 20
devices: 2
sync_batchnorm: True
accelerator: "gpu"
strategy: ddp
precision: 16-mixed
no_validation: True # important since we have no validation split
limit_val_batches: 0
num_sanity_val_steps: 0
log_every_n_steps: 200 # increase for larger runs
limit_train_batches: 0.25 # percentile or total batches (1.0 for full run)