defaults:
  - _self_
  - augmentations: asymmetric.yaml
  - wandb: private.yaml
  - override hydra/hydra_logging: disabled
  - override hydra/job_logging: disabled

# disable hydra outputs
hydra:
  output_subdir: null
  run:
    dir: .

name: "mocov3-cifar10" # change here for cifar100
method: "mocov3"
backbone:
  name: "resnet18"
method_kwargs:
  proj_hidden_dim: 2048
  proj_output_dim: 256
  pred_hidden_dim: 2048
  temperature: 0.2
momentum:
  base_tau: 0.99
  final_tau: 1.0
data:
  dataset: cifar10 # change here for cifar100
  train_path: "/home/elias/solo-learn/datasets"
  val_path: "/home/elias/solo-learn/datasets"
  format: "image_folder"
  num_workers: 4
optimizer:
  name: "lars"
  batch_size: 64
  lr: 0.075
  classifier_lr: 0.3
  weight_decay: 1e-6
  kwargs:
    clip_lr: True
    eta: 0.02
    exclude_bias_n_norm: True
scheduler:
  name: "warmup_cosine"
checkpoint:
  enabled: True
  dir: "trained_models"
  frequency: 1
auto_resume:
  enabled: True
knn_clb:
  enabled: True
  dataset: cifar10
  train_path:  "/home/elias/solo-learn/datasets"
  val_path:  "/home/elias/solo-learn/datasets"
  num_workers: 4
  batch_size: 16
  k: [ 10, 20, 50, 100 ]
  perform_on_validation: True
  verbose: True

# overwrite PL stuff
max_epochs: 1
devices: 2
sync_batchnorm: False
accelerator: "gpu"
strategy: ddp
precision: 16-mixed
