defaults:
  - _self_
  - wandb: private.yaml
  - override hydra/hydra_logging: disabled
  - override hydra/job_logging: disabled

# disable hydra outputs
hydra:
  output_subdir: null
  run:
    dir: .

name: "mocov3-imagenet-linear-minitest0"
pretrained_feature_extractor: trained_models/mocov3/g256yzz0/mocov3-ego4d-lrsweep1-g256yzz0-ep=0.ckpt
backbone:
  name: "resnet50"
pretrain_method: "mocov3"
data:
  dataset: imagenet
  train_path: "/home/data/ILSVRC_real/train" 
  val_path: "/home/data/ILSVRC_real/val"
  format: "image_folder"
  num_workers: 4
optimizer:
  name: "sgd"
  batch_size: 256
  lr: 0.3
  weight_decay: 0
scheduler:
  name: "step"
  lr_decay_steps: [60, 80]
checkpoint:
  enabled: True
  dir: "trained_models"
  frequency: 1
auto_resume:
  enabled: True

# overwrite PL stuff
max_epochs: 3
devices: [0]
sync_batchnorm: True
accelerator: "gpu"
strategy: "ddp"
precision: 16-mixed
limit_train_batches: 0.05 # percentile or total batches (1.0 for full run)
